#!/usr/bin/env node
/**
 * sync-catalog.mjs — re-derive the Tesseract component inventory from the live
 * storybook source so the skill stays current as the design system evolves.
 *
 * It scans src/components/{atoms,molecules}, reads the barrel exports and each
 * component's public prop destructure, and writes a generated inventory to
 *   references/_generated-inventory.md
 *
 * This file is a SNAPSHOT for reconciliation — it does NOT overwrite the
 * hand-curated component-catalog.md (which holds the "use it when" judgement).
 * After running, diff the two and fold any new/changed components into the
 * curated catalog by hand.
 *
 * Run from the repo root:
 *   node .claude/skills/tesseract-page-builder/scripts/sync-catalog.mjs
 */

import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const skillDir = resolve(scriptDir, "..");

// Repo root is 4 levels above the scripts dir; fall back to cwd if not found.
let root = resolve(scriptDir, "..", "..", "..", "..");
if (!existsSync(join(root, "src", "components"))) {
  if (existsSync(join(process.cwd(), "src", "components"))) {
    root = process.cwd();
  } else {
    console.error("Could not locate src/components. Run from the repo root.");
    process.exit(1);
  }
}

const LAYERS = ["atoms", "molecules", "charts"];

/** Parse a barrel index.js into a list of exported names. */
function parseBarrel(indexPath) {
  if (!existsSync(indexPath)) return [];
  const src = readFileSync(indexPath, "utf8");
  const names = new Set();
  // matches: export { A, B as C } from "./X";  and  export { A } from "./X";
  const re = /export\s*\{([^}]+)\}\s*from/g;
  let m;
  while ((m = re.exec(src))) {
    for (const part of m[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/).pop().trim();
      if (name) names.add(name);
    }
  }
  return [...names];
}

/** Extract `export function Name({ a, b, c })` prop lists from a component file. */
function extractProps(fileSrc) {
  const out = {};
  const re = /export\s+function\s+([A-Z][A-Za-z0-9_]*)\s*\(\s*\{([\s\S]*?)\}\s*\)/g;
  let m;
  while ((m = re.exec(fileSrc))) {
    const name = m[1];
    const body = m[2];
    const props = [];
    // top-level prop names: split on commas not inside nested braces/brackets/parens
    let depth = 0, token = "";
    for (const ch of body) {
      if ("({[".includes(ch)) depth++;
      else if (")}]".includes(ch)) depth--;
      if (ch === "," && depth === 0) { props.push(token); token = ""; }
      else token += ch;
    }
    if (token.trim()) props.push(token);
    out[name] = props
      .map((p) => p.split(/[:=]/)[0].replace(/\.\.\./, "").trim())
      .filter((p) => p && /^[A-Za-z_]/.test(p));
  }
  return out;
}

/** Find component dirs under a layer and their primary jsx files. */
function scanLayer(layer) {
  const base = join(root, "src", "components", layer);
  if (!existsSync(base)) return [];
  const entries = readdirSync(base).filter((name) => {
    if (name === "internal" || name === "icons") return false; // shared helpers, not public components
    const p = join(base, name);
    return statSync(p).isDirectory();
  });
  const comps = [];
  for (const dir of entries) {
    const dirPath = join(base, dir);
    const files = readdirSync(dirPath).filter((f) => f.endsWith(".jsx") && !f.endsWith(".stories.jsx"));
    let propsByName = {};
    for (const f of files) {
      try {
        Object.assign(propsByName, extractProps(readFileSync(join(dirPath, f), "utf8")));
      } catch { /* skip unreadable */ }
    }
    comps.push({ dir, exports: propsByName });
  }
  return comps;
}

const now = new Date().toISOString().slice(0, 10);
let md = `<!-- AUTO-GENERATED by scripts/sync-catalog.mjs on ${now}. Do not hand-edit. -->\n`;
md += `# Generated Component Inventory (snapshot)\n\n`;
md += `Reconcile against \`component-catalog.md\`; fold new/changed components into the curated catalog by hand.\n`;

for (const layer of LAYERS) {
  const barrel = parseBarrel(join(root, "src", "components", layer, "index.js"));
  const comps = scanLayer(layer);
  md += `\n## ${layer} — ${barrel.length} barrel exports\n\n`;
  md += `Exports: ${barrel.sort().join(", ") || "(none parsed)"}\n\n`;
  md += `| Component dir | Exported fn | Public props (top-level) |\n|---|---|---|\n`;
  for (const c of comps.sort((a, b) => a.dir.localeCompare(b.dir))) {
    const names = Object.keys(c.exports);
    if (names.length === 0) {
      md += `| ${c.dir} | — | _(no \`export function Name({…})\` found; may use const/arrow — check source)_ |\n`;
      continue;
    }
    for (const fn of names) {
      const props = c.exports[fn];
      md += `| ${c.dir} | \`${fn}\` | ${props.length ? props.map((p) => `\`${p}\``).join(", ") : "—"} |\n`;
    }
  }
}

const outPath = join(skillDir, "references", "_generated-inventory.md");
writeFileSync(outPath, md, "utf8");
console.log(`Wrote ${outPath}`);
console.log(`Scanned ${root}/src/components/{${LAYERS.join(",")}}`);
console.log(`Next: diff against references/component-catalog.md and reconcile by hand.`);
