export const tpMedicalIconRegistry = {
  "ambulance": { line: "/tp-icons/medical/ambulance--line.svg", bulk: "/tp-icons/medical/ambulance--bulk.svg", solid: "/tp-icons/medical/ambulance--solid.svg" },
  "anxiety": { line: "/tp-icons/medical/anxiety--line.svg", bulk: "/tp-icons/medical/anxiety--bulk.svg", solid: "/tp-icons/medical/anxiety--solid.svg" },
  "bandage": { line: "/tp-icons/medical/bandage--line.svg", bulk: "/tp-icons/medical/bandage--bulk.svg", solid: "/tp-icons/medical/bandage--solid.svg" },
  "bandage-02": { line: "/tp-icons/medical/bandage-02--line.svg", bulk: "/tp-icons/medical/bandage-02--bulk.svg", solid: "/tp-icons/medical/bandage-02--solid.svg" },
  "blood": { line: "/tp-icons/medical/blood--line.svg", bulk: "/tp-icons/medical/blood--bulk.svg", solid: "/tp-icons/medical/blood--solid.svg" },
  "blood 3": { line: "/tp-icons/medical/blood-3--line.svg", bulk: "/tp-icons/medical/blood-3--bulk.svg", solid: "/tp-icons/medical/blood-3--solid.svg" },
  "brain": { line: "/tp-icons/medical/brain--line.svg", bulk: "/tp-icons/medical/brain--bulk.svg", solid: "/tp-icons/medical/brain--solid.svg" },
  "call-hospital": { line: "/tp-icons/medical/call-hospital--line.svg", bulk: "/tp-icons/medical/call-hospital--bulk.svg", solid: "/tp-icons/medical/call-hospital--solid.svg" },
  "capsule 3": { line: "/tp-icons/medical/capsule-3--line.svg", bulk: "/tp-icons/medical/capsule-3--bulk.svg", solid: "/tp-icons/medical/capsule-3--solid.svg" },
  "cardiogram": { line: "/tp-icons/medical/cardiogram--line.svg", bulk: "/tp-icons/medical/cardiogram--bulk.svg", solid: "/tp-icons/medical/cardiogram--solid.svg" },
  "clipboard-activity": { line: "/tp-icons/medical/clipboard-activity--line.svg", bulk: "/tp-icons/medical/clipboard-activity--bulk.svg", solid: "/tp-icons/medical/clipboard-activity--solid.svg" },
  "Diagnosis": { line: "/tp-icons/medical/diagnosis--line.svg", bulk: "/tp-icons/medical/diagnosis--bulk.svg", solid: "/tp-icons/medical/diagnosis--solid.svg" },
  "DNA": { line: "/tp-icons/medical/dna--line.svg", bulk: "/tp-icons/medical/dna--bulk.svg", solid: "/tp-icons/medical/dna--solid.svg" },
  "ectrocardiogram-monitor-02": { line: "/tp-icons/medical/ectrocardiogram-monitor-02--line.svg", bulk: "/tp-icons/medical/ectrocardiogram-monitor-02--bulk.svg", solid: "/tp-icons/medical/ectrocardiogram-monitor-02--solid.svg" },
  "electrocardiogram-monitor-01": { line: "/tp-icons/medical/electrocardiogram-monitor-01--line.svg", bulk: "/tp-icons/medical/electrocardiogram-monitor-01--bulk.svg", solid: "/tp-icons/medical/electrocardiogram-monitor-01--solid.svg" },
  "emergency": { line: "/tp-icons/medical/emergency--line.svg", bulk: "/tp-icons/medical/emergency--bulk.svg", solid: "/tp-icons/medical/emergency--solid.svg" },
  "empathy": { line: "/tp-icons/medical/empathy--line.svg", bulk: "/tp-icons/medical/empathy--bulk.svg", solid: "/tp-icons/medical/empathy--solid.svg" },
  "eye": { line: "/tp-icons/medical/eye--line.svg", bulk: "/tp-icons/medical/eye--bulk.svg", solid: "/tp-icons/medical/eye--solid.svg" },
  "first-aid": { line: "/tp-icons/medical/first-aid--line.svg", bulk: "/tp-icons/medical/first-aid--bulk.svg", solid: "/tp-icons/medical/first-aid--solid.svg" },
  "give-blood": { line: "/tp-icons/medical/give-blood--line.svg", bulk: "/tp-icons/medical/give-blood--bulk.svg", solid: "/tp-icons/medical/give-blood--solid.svg" },
  "give-pill": { line: "/tp-icons/medical/give-pill--line.svg", bulk: "/tp-icons/medical/give-pill--bulk.svg", solid: "/tp-icons/medical/give-pill--solid.svg" },
  "Gynec": { line: "/tp-icons/medical/gynec--line.svg", bulk: "/tp-icons/medical/gynec--bulk.svg", solid: "/tp-icons/medical/gynec--solid.svg" },
  "hand-soap": { line: "/tp-icons/medical/hand-soap--line.svg", bulk: "/tp-icons/medical/hand-soap--bulk.svg", solid: "/tp-icons/medical/hand-soap--solid.svg" },
  "health care": { line: "/tp-icons/medical/health-care--line.svg", bulk: "/tp-icons/medical/health-care--bulk.svg", solid: "/tp-icons/medical/health-care--solid.svg" },
  "health-file-02": { line: "/tp-icons/medical/health-file-02--line.svg", bulk: "/tp-icons/medical/health-file-02--bulk.svg", solid: "/tp-icons/medical/health-file-02--solid.svg" },
  "health-file-03": { line: "/tp-icons/medical/health-file-03--line.svg", bulk: "/tp-icons/medical/health-file-03--bulk.svg", solid: "/tp-icons/medical/health-file-03--solid.svg" },
  "health-folder": { line: "/tp-icons/medical/health-folder--line.svg", bulk: "/tp-icons/medical/health-folder--bulk.svg", solid: "/tp-icons/medical/health-folder--solid.svg" },
  "Heart Rate": { line: "/tp-icons/medical/heart-rate--line.svg", bulk: "/tp-icons/medical/heart-rate--bulk.svg", solid: "/tp-icons/medical/heart-rate--solid.svg" },
  "Heart Rate Monitor": { line: "/tp-icons/medical/heart-rate-monitor--line.svg", bulk: "/tp-icons/medical/heart-rate-monitor--bulk.svg", solid: "/tp-icons/medical/heart-rate-monitor--solid.svg" },
  "HIV": { line: "/tp-icons/medical/hiv--line.svg", bulk: "/tp-icons/medical/hiv--bulk.svg", solid: "/tp-icons/medical/hiv--solid.svg" },
  "hospital": { line: "/tp-icons/medical/hospital--line.svg", bulk: "/tp-icons/medical/hospital--bulk.svg", solid: "/tp-icons/medical/hospital--solid.svg" },
  "hospital 3": { line: "/tp-icons/medical/hospital-3--line.svg", bulk: "/tp-icons/medical/hospital-3--bulk.svg", solid: "/tp-icons/medical/hospital-3--solid.svg" },
  "Hospital Building 3": { line: "/tp-icons/medical/hospital-building-3--line.svg", bulk: "/tp-icons/medical/hospital-building-3--bulk.svg", solid: "/tp-icons/medical/hospital-building-3--solid.svg" },
  "Hospital Building 4": { line: "/tp-icons/medical/hospital-building-4--line.svg", bulk: "/tp-icons/medical/hospital-building-4--bulk.svg", solid: "/tp-icons/medical/hospital-building-4--solid.svg" },
  "hospital-bed": { line: "/tp-icons/medical/hospital-bed--line.svg", bulk: "/tp-icons/medical/hospital-bed--bulk.svg", solid: "/tp-icons/medical/hospital-bed--solid.svg" },
  "injection": { line: "/tp-icons/medical/injection--line.svg", bulk: "/tp-icons/medical/injection--bulk.svg", solid: "/tp-icons/medical/injection--solid.svg" },
  "Lab": { line: "/tp-icons/medical/lab--line.svg", bulk: "/tp-icons/medical/lab--bulk.svg", solid: "/tp-icons/medical/lab--solid.svg" },
  "lifebuoy": { line: "/tp-icons/medical/lifebuoy--line.svg", bulk: "/tp-icons/medical/lifebuoy--bulk.svg", solid: "/tp-icons/medical/lifebuoy--solid.svg" },
  "location-hospital": { line: "/tp-icons/medical/location-hospital--line.svg", bulk: "/tp-icons/medical/location-hospital--bulk.svg", solid: "/tp-icons/medical/location-hospital--solid.svg" },
  "lungs": { line: "/tp-icons/medical/lungs--line.svg", bulk: "/tp-icons/medical/lungs--bulk.svg", solid: "/tp-icons/medical/lungs--solid.svg" },
  "mask": { line: "/tp-icons/medical/mask--line.svg", bulk: "/tp-icons/medical/mask--bulk.svg", solid: "/tp-icons/medical/mask--solid.svg" },
  "medical book": { line: "/tp-icons/medical/medical-book--line.svg", bulk: "/tp-icons/medical/medical-book--bulk.svg", solid: "/tp-icons/medical/medical-book--solid.svg" },
  "Medical document": { line: "/tp-icons/medical/medical-document--line.svg", bulk: "/tp-icons/medical/medical-document--bulk.svg", solid: "/tp-icons/medical/medical-document--solid.svg" },
  "medical information": { line: "/tp-icons/medical/medical-information--line.svg", bulk: "/tp-icons/medical/medical-information--bulk.svg", solid: "/tp-icons/medical/medical-information--solid.svg" },
  "medical service": { line: "/tp-icons/medical/medical-service--line.svg", bulk: "/tp-icons/medical/medical-service--bulk.svg", solid: "/tp-icons/medical/medical-service--solid.svg" },
  "medical-file": { line: "/tp-icons/medical/medical-file--line.svg", bulk: "/tp-icons/medical/medical-file--bulk.svg", solid: "/tp-icons/medical/medical-file--solid.svg" },
  "medical-record": { line: "/tp-icons/medical/medical-record--line.svg", bulk: "/tp-icons/medical/medical-record--bulk.svg", solid: "/tp-icons/medical/medical-record--solid.svg" },
  "medical-report": { line: "/tp-icons/medical/medical-report--line.svg", bulk: "/tp-icons/medical/medical-report--bulk.svg", solid: "/tp-icons/medical/medical-report--solid.svg" },
  "mental-health": { line: "/tp-icons/medical/mental-health--line.svg", bulk: "/tp-icons/medical/mental-health--bulk.svg", solid: "/tp-icons/medical/mental-health--solid.svg" },
  "microscope": { line: "/tp-icons/medical/microscope--line.svg", bulk: "/tp-icons/medical/microscope--bulk.svg", solid: "/tp-icons/medical/microscope--solid.svg" },
  "Obstetric": { line: "/tp-icons/medical/obstetric--line.svg", bulk: "/tp-icons/medical/obstetric--bulk.svg", solid: "/tp-icons/medical/obstetric--solid.svg" },
  "operating-scissors-01": { line: "/tp-icons/medical/operating-scissors-01--line.svg", bulk: "/tp-icons/medical/operating-scissors-01--bulk.svg", solid: "/tp-icons/medical/operating-scissors-01--solid.svg" },
  "pill": { line: "/tp-icons/medical/pill--line.svg", bulk: "/tp-icons/medical/pill--bulk.svg", solid: "/tp-icons/medical/pill--solid.svg" },
  "pill-tablet": { line: "/tp-icons/medical/pill-tablet--line.svg", bulk: "/tp-icons/medical/pill-tablet--bulk.svg", solid: "/tp-icons/medical/pill-tablet--solid.svg" },
  "pills 3": { line: "/tp-icons/medical/pills-3--line.svg", bulk: "/tp-icons/medical/pills-3--bulk.svg", solid: "/tp-icons/medical/pills-3--solid.svg" },
  "plaster": { line: "/tp-icons/medical/plaster--line.svg", bulk: "/tp-icons/medical/plaster--bulk.svg", solid: "/tp-icons/medical/plaster--solid.svg" },
  "stethoscope": { line: "/tp-icons/medical/stethoscope--line.svg", bulk: "/tp-icons/medical/stethoscope--bulk.svg", solid: "/tp-icons/medical/stethoscope--solid.svg" },
  "stomach-care": { line: "/tp-icons/medical/stomach-care--line.svg", bulk: "/tp-icons/medical/stomach-care--bulk.svg", solid: "/tp-icons/medical/stomach-care--solid.svg" },
  "surgical-scissors-02": { line: "/tp-icons/medical/surgical-scissors-02--line.svg", bulk: "/tp-icons/medical/surgical-scissors-02--bulk.svg", solid: "/tp-icons/medical/surgical-scissors-02--solid.svg" },
  "syrup": { line: "/tp-icons/medical/syrup--line.svg", bulk: "/tp-icons/medical/syrup--bulk.svg", solid: "/tp-icons/medical/syrup--solid.svg" },
  "Tablets": { line: "/tp-icons/medical/tablets--line.svg", bulk: "/tp-icons/medical/tablets--bulk.svg", solid: "/tp-icons/medical/tablets--solid.svg" },
  "Test Tube": { line: "/tp-icons/medical/test-tube--line.svg", bulk: "/tp-icons/medical/test-tube--bulk.svg", solid: "/tp-icons/medical/test-tube--solid.svg" },
  "test-tube-02": { line: "/tp-icons/medical/test-tube-02--line.svg", bulk: "/tp-icons/medical/test-tube-02--bulk.svg", solid: "/tp-icons/medical/test-tube-02--solid.svg" },
  "thermometer": { line: "/tp-icons/medical/thermometer--line.svg", bulk: "/tp-icons/medical/thermometer--bulk.svg", solid: "/tp-icons/medical/thermometer--solid.svg" },
  "tooth": { line: "/tp-icons/medical/tooth--line.svg", bulk: "/tp-icons/medical/tooth--bulk.svg", solid: "/tp-icons/medical/tooth--solid.svg" },
  "transfusion": { line: "/tp-icons/medical/transfusion--line.svg", bulk: "/tp-icons/medical/transfusion--bulk.svg", solid: "/tp-icons/medical/transfusion--solid.svg" },
  "ultrasound-monitor-01": { line: "/tp-icons/medical/ultrasound-monitor-01--line.svg", bulk: "/tp-icons/medical/ultrasound-monitor-01--bulk.svg", solid: "/tp-icons/medical/ultrasound-monitor-01--solid.svg" },
  "ultrasound-monitor-02": { line: "/tp-icons/medical/ultrasound-monitor-02--line.svg", bulk: "/tp-icons/medical/ultrasound-monitor-02--bulk.svg", solid: "/tp-icons/medical/ultrasound-monitor-02--solid.svg" },
  "Virus": { line: "/tp-icons/medical/virus--line.svg", bulk: "/tp-icons/medical/virus--bulk.svg", solid: "/tp-icons/medical/virus--solid.svg" },
  "virus-lab-research": { line: "/tp-icons/medical/virus-lab-research--line.svg", bulk: "/tp-icons/medical/virus-lab-research--bulk.svg", solid: "/tp-icons/medical/virus-lab-research--solid.svg" },
  "wheel chair 3": { line: "/tp-icons/medical/wheel-chair-3--line.svg", bulk: "/tp-icons/medical/wheel-chair-3--bulk.svg", solid: "/tp-icons/medical/wheel-chair-3--solid.svg" },
  "wheelchair": { line: "/tp-icons/medical/wheelchair--line.svg", bulk: "/tp-icons/medical/wheelchair--bulk.svg", solid: "/tp-icons/medical/wheelchair--solid.svg" }
};




export const tpMedicalIconNames = Object.keys(tpMedicalIconRegistry);

const tpMedicalIconAliasMap = {
  "ambulance": "ambulance",
  "anxiety": "anxiety",
  "bandage": "bandage",
  "bandage 02": "bandage-02",
  "bandage-02": "bandage-02",
  "blood": "blood",
  "blood 3": "blood 3",
  "blood-3": "blood 3",
  "blood3": "blood 3",
  "brain": "brain",
  "call hospital": "call-hospital",
  "call-hospital": "call-hospital",
  "capsule 3": "capsule 3",
  "capsule-3": "capsule 3",
  "capsule3": "capsule 3",
  "cardiogram": "cardiogram",
  "clipboard activity": "clipboard-activity",
  "clipboard-activity": "clipboard-activity",
  "diagnosis": "Diagnosis",
  "Diagnosis": "Diagnosis",
  // ── VoiceRx section tokens — kept in lock-step with the icons the
  // working RxPad surfaces use (see RxPadFunctional), so the EMR
  // section bars in the chat card and the sections in the editable
  // RxPad read as the *same* family. Colour is applied at the call
  // site (slate-500 in the chat card, violet-500 in the RxPad).
  "symptom": "Virus",
  "symptoms": "Virus",
  "examination": "medical service",
  "examinations": "medical service",
  "medication": "Tablets",
  "medications": "Tablets",
  "advice": "health care",
  "surgery": "surgical-scissors-02",
  "surgeries": "surgical-scissors-02",
  "investigation": "Test Tube",
  "investigations": "Test Tube",
  "labInvestigation": "Test Tube",
  "labInvestigations": "Test Tube",
  "lab investigation": "Test Tube",
  "lab investigations": "Test Tube",
  "labResults": "Test Tube",
  "lab results": "Test Tube",
  "labadministration": "Test Tube",
  "lab administration": "Test Tube",
  "lab-administration": "Test Tube",
  "vital": "Heart Rate",
  "vitals": "Heart Rate",
  "history": "medical-record",
  "histories": "medical-record",
  "followUp": "clipboard-activity",
  "follow up": "clipboard-activity",
  "follow-up": "clipboard-activity",
  "dna": "DNA",
  "DNA": "DNA",
  "ectrocardiogram monitor 02": "ectrocardiogram-monitor-02",
  "ectrocardiogram-monitor-02": "ectrocardiogram-monitor-02",
  "electrocardiogram monitor 01": "electrocardiogram-monitor-01",
  "electrocardiogram-monitor-01": "electrocardiogram-monitor-01",
  "emergency": "emergency",
  "empathy": "empathy",
  "eye": "eye",
  "first aid": "first-aid",
  "first-aid": "first-aid",
  "give blood": "give-blood",
  "give pill": "give-pill",
  "give-blood": "give-blood",
  "give-pill": "give-pill",
  "gynec": "Gynec",
  "Gynec": "Gynec",
  "gynaec": "Gynec",
  "hand soap": "hand-soap",
  "hand-soap": "hand-soap",
  "health care": "health care",
  "health file 02": "health-file-02",
  "health file 03": "health-file-03",
  "health folder": "health-folder",
  "health-care": "health care",
  "health-file-02": "health-file-02",
  "health-file-03": "health-file-03",
  "health-folder": "health-folder",
  "healthcare": "health care",
  "heart rate": "Heart Rate",
  "Heart Rate": "Heart Rate",
  "heart rate monitor": "Heart Rate Monitor",
  "Heart Rate Monitor": "Heart Rate Monitor",
  "heart-rate": "Heart Rate",
  "heart-rate-monitor": "Heart Rate Monitor",
  "heartrate": "Heart Rate",
  "heartratemonitor": "Heart Rate Monitor",
  "hiv": "HIV",
  "HIV": "HIV",
  "hospital": "hospital",
  "hospital 3": "hospital 3",
  "hospital bed": "hospital-bed",
  "hospital building 3": "Hospital Building 3",
  "Hospital Building 3": "Hospital Building 3",
  "hospital building 4": "Hospital Building 4",
  "Hospital Building 4": "Hospital Building 4",
  "hospital-3": "hospital 3",
  "hospital-bed": "hospital-bed",
  "hospital-building-3": "Hospital Building 3",
  "hospital-building-4": "Hospital Building 4",
  "hospital3": "hospital 3",
  "hospitalbuilding3": "Hospital Building 3",
  "hospitalbuilding4": "Hospital Building 4",
  "injection": "injection",
  "lab": "Lab",
  "Lab": "Lab",
  "lifebuoy": "lifebuoy",
  "location hospital": "location-hospital",
  "location-hospital": "location-hospital",
  "lungs": "lungs",
  "mask": "mask",
  "medical book": "medical book",
  "medical document": "Medical document",
  "Medical document": "Medical document",
  "medical file": "medical-file",
  "medical information": "medical information",
  "medical record": "medical-record",
  "medical report": "medical-report",
  "medical service": "medical service",
  "medical-book": "medical book",
  "medical-document": "Medical document",
  "medical-file": "medical-file",
  "medical-information": "medical information",
  "medical-record": "medical-record",
  "medical-report": "medical-report",
  "medical-service": "medical service",
  "medicalbook": "medical book",
  "medicaldocument": "Medical document",
  "medicalinformation": "medical information",
  "medicalservice": "medical service",
  "mental health": "mental-health",
  "mental-health": "mental-health",
  "microscope": "microscope",
  "obstetric": "Obstetric",
  "Obstetric": "Obstetric",
  "operating scissors 01": "operating-scissors-01",
  "operating-scissors-01": "operating-scissors-01",
  "pill": "pill",
  "pill tablet": "pill-tablet",
  "pill-tablet": "pill-tablet",
  "pills 3": "pills 3",
  "pills-3": "pills 3",
  "pills3": "pills 3",
  "plaster": "plaster",
  "stethoscope": "stethoscope",
  "stomach care": "stomach-care",
  "stomach-care": "stomach-care",
  "surgical scissors 02": "surgical-scissors-02",
  "surgical-scissors-02": "surgical-scissors-02",
  "syrup": "syrup",
  "tablets": "Tablets",
  "Tablets": "Tablets",
  "test tube": "Test Tube",
  "Test Tube": "Test Tube",
  "test tube 02": "test-tube-02",
  "test-tube": "Test Tube",
  "test-tube-02": "test-tube-02",
  "testtube": "Test Tube",
  "thermometer": "thermometer",
  "tooth": "tooth",
  "transfusion": "transfusion",
  "ultrasound monitor 01": "ultrasound-monitor-01",
  "ultrasound monitor 02": "ultrasound-monitor-02",
  "ultrasound-monitor-01": "ultrasound-monitor-01",
  "ultrasound-monitor-02": "ultrasound-monitor-02",
  "virus": "Virus",
  "Virus": "Virus",
  "virus lab research": "virus-lab-research",
  "virus-lab-research": "virus-lab-research",
  "wheel chair 3": "wheel chair 3",
  "wheel-chair-3": "wheel chair 3",
  "wheelchair": "wheelchair",
  "wheelchair3": "wheel chair 3"
};

export function resolveTPMedicalIconName(name) {
  const direct = tpMedicalIconAliasMap[name] ?? tpMedicalIconAliasMap[name.trim()];
  if (direct) return direct;
  const normalized = name.trim().toLowerCase().replace(/[_.-]+/g, " ").replace(/\s+/g, " ");
  return tpMedicalIconAliasMap[normalized] ?? null;
}